### ISSUE TITLE
OptionParser::AmbiguousOption: ambiguous option:

### ISSUE THREAD

**Issue by nfedyashev** [carhartl/guard-pusher#1]
Hi Klaus!

Thanks for the gem! I was really excited about trying it out in my project.

I know it is a bit outdated but perhaps you have an idea on what might be causing this issue.
Just adding it to Gemfile(gem 'guard-pusher') causes this error:

```
rails_1     | bin/rails:6: warning: already initialized constant APP_PATH
rails_1     | /app/bin/rails:6: warning: previous definition of APP_PATH was here
rails_1     | rails aborted!
rails_1     | OptionParser::AmbiguousOption: ambiguous option: -b
rails_1     | /bundle/gems/railties-5.2.4/lib/rails/commands/rake/rake_command.rb:21:in `block in perform'
rails_1     | /bundle/gems/railties-5.2.4/lib/rails/commands/rake/rake_command.rb:20:in `perform'
rails_1     | /bundle/gems/railties-5.2.4/lib/rails/command.rb:48:in `invoke'
rails_1     | /bundle/gems/railties-5.2.4/lib/rails/commands.rb:18:in `<top (required)>'
rails_1     | /bundle/gems/activesupport-5.2.4/lib/active_support/dependencies.rb:291:in `require'
rails_1     | /bundle/gems/activesupport-5.2.4/lib/active_support/dependencies.rb:291:in `block in require'
rails_1     | /bundle/gems/activesupport-5.2.4/lib/active_support/dependencies.rb:257:in `load_dependency'
rails_1     | /bundle/gems/activesupport-5.2.4/lib/active_support/dependencies.rb:291:in `require'
rails_1     | bin/rails:8:in `<main>'
rails_1     | 
rails_1     | Caused by:
rails_1     | OptionParser::InvalidOption: invalid option: b
rails_1     | /bundle/gems/railties-5.2.4/lib/rails/commands/rake/rake_command.rb:21:in `block in perform'
rails_1     | /bundle/gems/railties-5.2.4/lib/rails/commands/rake/rake_command.rb:20:in `perform'
rails_1     | /bundle/gems/railties-5.2.4/lib/rails/command.rb:48:in `invoke'
rails_1     | /bundle/gems/railties-5.2.4/lib/rails/commands.rb:18:in `<top (required)>'
rails_1     | /bundle/gems/activesupport-5.2.4/lib/active_support/dependencies.rb:291:in `require'
rails_1     | /bundle/gems/activesupport-5.2.4/lib/active_support/dependencies.rb:291:in `block in require'
rails_1     | /bundle/gems/activesupport-5.2.4/lib/active_support/dependencies.rb:257:in `load_dependency'
rails_1     | /bundle/gems/activesupport-5.2.4/lib/active_support/dependencies.rb:291:in `require'
rails_1     | bin/rails:8:in `<main>'
rails_1     | (See full trace by running task with --trace)
```

Ruby 2.6.3
Rails 5.2.4

**Comment by nfedyashev** [comment]
Some debug info: 

Pusher client's API seems to be still compatible with that old version.
But to make a successful request I had to explicitly set "cluster" config setting.

**Comment by carhartl** [comment]
I have no idea..

**Comment by carhartl** [comment]
Did you go through https://github.com/guard/guard/blob/master/README.md#installation ?

**Comment by nfedyashev** [comment]
@carhartl yes, guard is installed.
Other plugins(guard-rspec, guard-yield) don't trigger any warnings in my case.

As a workaround, I'm using guard-yield plugin with an explicit proc calling Pusher['guard-pusher'] trigger.
